### ISSUE TITLE
Local Linear Regression asking for date field input

### ISSUE THREAD

**Issue by unmonoqueteclea** [bigmlcom/python#272]
When trying to create a prediction from a Local Linear Regression that contains a date field, an exception is raised because the input must contain values for the date field (although all the date sub-fields from this field are in the input. This is the exception raised:

`File "/Users/unmonoqueteclea/github/unmonoqueteclea/python/bigml/util.py", line 619, in check_no_training_missings
    "to get a prediction." % field['name'])
ValueError: Failed to predict. Input data must contain values for field 'test-date' to get a prediction.`

And this is the code I used:

```
from bigml.api import BigML
from bigml.linear import LinearRegression

api = BigML()
content = [["test-date","test-num1","test-num2", "test-num3"],
           ["01/12/2012",23,34,54],
           ["13/12/1998",22,54,65],
           ["15/04/2002",25,56,70],
           ["17/12/2012",23,30,54],
           ["24/03/1998",22,54,65],
           ["30/04/2002",25,23,70],
           ["23/12/2012",23,76,54],
           ["21/04/1998",22,87,65],
           ["30/06/2002",25,56,90],
           ["23/11/2012",23,98,9],
           ["07/12/1998",22,54,34],
           ["30/04/2002",25,23,12]]

source = api.create_source(content)
dataset = api.create_dataset(source)
api.ok(dataset)
model_args = {"objective_field": "test-num3"}
lr = api.create_linear_regression(dataset, model_args)
api.ok(lr)
local_lr= LinearRegression(lr)
options = {"test-num1": 23,
           "test-num2" : 54,
           "test-date.day-of-month":2,
           "test-date.month":12,
           "test-date.day-of-week": 2,
           "test-date.year": 2012}

print(local_lr.predict(options)) # Exception raised
```

Don't know if it's the correct way of doing things but adding a line to  **check_no_training_missings** to filter non-preferred fields solves the issue. I can create a PR if needed:

```
def check_no_training_missings(input_data, fields, weight_field=None,
                               objective_id=None):
    """Checks whether some input fields are missing in the input data
    while not training data has no missings in that field

    """
    for field_id, field in fields.items():
      if (field["preferred"] and \
          (not field_id in input_data and \
            field['summary']['missing_count'] == 0 and \
                (weight_field is None or \
                field_id != weight_field) and \
                (objective_id is None or field_id != objective_id))):
            raise ValueError("Failed to predict. Input"
                             " data must contain values for field '%s' "
                             "to get a prediction." % field['name'])
```

**Comment by mmerce** [comment]
Hi there,

yes, you're right about the fact that the fields to be checked are not the ones that are currently being used. However, I think the problem goes beyond filtering the non-preferred fields. Probably, what we should do is checking only the fields that have been used in the model construction: input_fields, so it's probably better to filter out the fields that are not used in the model before calling the function, and that can be done in the constructor. That would improve efficiency, because this function in called for each prediction, while the constructor is only called once.

I remember adapting the code to do that previously, somewhere but I refactored these functions lately, so it's a reapearing bug, I'm a fraid. Thanks for the heads up!

**Comment by mmerce** [comment]
PR #273 wants to solve that, even if probably the solution will be provided by the backend later.
